[package]
name = "rectangle_animation"
version = "0.1.0"
authors = ["Ilya Revenko <ilya.revenko17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window="*"
rand="*"
